// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlcryymdrdcbgrajkwbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsY3J5eW1kcmRjYmdyYWprd2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTIyNjQsImV4cCI6MjA1NzYyODI2NH0.q4WSpFhthkPa2X1ZysrK_3r_iyhHhJ2LqfkMNz5NtqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);